### ISSUE TITLE
"Embed" assignment detail pages in between navbar and footer on our website

### ISSUE THREAD

**Issue by leedsjb** [leedsjb/info343-group-project#16]

**Comment by leedsjb** [comment]
If we have time we should "embed" (read: copy the HTML) the assignment detail pages on our website. This way when an assignment detail link is clicked the user does not leave our website to the old website and can easily click other links to navigate elsewhere.

**Comment by brookslobe** [comment]
We could also do this for the lab pages that are linked from the calendar right now.  I have all the files in the lab pages saved to the assets folder, but the fact that it has downloads means a lot of links, unlike the native Homework pages.
