### ISSUE TITLE
Fix spacing of footer elements

### ISSUE THREAD

**Issue by brookslobe** [leedsjb/info343-group-project#28]
Social media links on the right side need to be the same distance away from the right edge as the class info on the left side is from the left edge.

Seattle Central College link in the middle needs to be centered.  Or removed...I think it looks tacky to have that in the footer.

**Comment by leedsjb** [comment]
@brookslobe Let's add this link in the footer:

http://docs.oracle.com/javase/8/docs/api/index.html

With the text Java API Documentation

We use this link extremely often in class so it merits its presence in the footer instead of "Seattle Central" as you suggested.

**Comment by bkhoy** [comment]
I just pushed my own rendition of the footer

**Comment by briluu** [comment]
I GIVE MY APPROVAL :+1:

**Comment by brookslobe** [comment]
At around <992px part of the footer disappears now D:

**Comment by leedsjb** [comment]
@brookslobe Confirmed, I see that as well.

**Comment by briluu** [comment]
yeah okay brittney's rendition is actually not mobile friendly. ill try to fix it for now

**Comment by briluu** [comment]
okay I fixed the spacing of the footer and its mobile friendly. however I still kinda liked the previous version but oh well
