### ISSUE TITLE
Class Note PDFs and PPTs are broken links on deployed website on server

### ISSUE THREAD

**Issue by leedsjb** [leedsjb/info343-group-project#34]

**Comment by briluu** [comment]
This seems like a pretty weird bug, since it worked locally. Perhaps it may be due to uploading (way) too many files to our student servers. Or perhaps we're not allowed to host PDFs on the server?

**Comment by leedsjb** [comment]
Found the issue! When you reference a URL on a webpage if there's a "/" at the beginning it appends the URL to the root URL, i.e.:

rootURL: students.washington.edu
url in href: /assets/notes/power/01-modeling.ppt

Which resolves to: students.washington.edu/assets/notes/power/01-modeling.ppt

But that URL doesn't exist. The correct URL is: 

http://students.washington.edu/leeds/info343/info343-group-project/assets/notes/pdf/01-modeling.pdf

**To fix the problem, I simply removed the "/" from the beginning of /assets/notes/power/01-modeling.ppt**
