### ISSUE TITLE
Class note download buttons misaligned after search and page resize

### ISSUE THREAD

**Issue by leedsjb** [leedsjb/info343-group-project#36]
**Able to reproduce several times in a row but now cannot. Let me know if you see this issue as well.**

Steps to reproduce:
1. Start on the class notes page
2. Start on the desktop size viewport.
3. Narrow to mobile size. 
4. Enter the search query "a"
5. Expand back to desktop size

<img width="1228" alt="screen shot 2015-12-11 at 1 05 46 am" src="https://cloud.githubusercontent.com/assets/14936177/11739870/697c776e-9fa3-11e5-9db7-eced38d87c85.png">

**Comment by brookslobe** [comment]
Haven't seen the issue before.  Also couldn't get it to occur after following your steps.
